### ISSUE TITLE
where can i find db structure for comment box

### ISSUE THREAD

**Issue by prasadraja07** [Viima/jquery-comments#100]
Can you share the db structure for the comment plugin....so it wil be clear to implement

**Comment by bluesun3k1** [comment]
I just started using this plugin a few days ago and you can't really find the db structure on here. The reason could be because the plugin allows you to customize it depending on your needs.

I for one did the following.

A table with the basic comment data such as, comment Id, parent id, page id, user Id, date created, date modified, comment content.

A table for upvotes that stores, post id, comment id, user id, vote date.

A table for downvotes (I had to implement this myself as downvoting doesn't come with the plugin).

And just joined tables as needed.

Hope those little details help.

**Comment by prasadraja07** [comment]
Even i also implement same as you explained..... just i would like to see the changes on my db, that some thing i may went wrong :)

**Comment by jessenieminen** [comment]
Hi guys, sorry for the delayed answer! Here's what our comments API looks like for reference purposes.

![comment api example](https://user-images.githubusercontent.com/1484449/28418183-8622b1fa-6d63-11e7-8747-5a4fc279b5a1.png)

**Comment by jessenieminen** [comment]
http://viima.github.io/jquery-comments/#link-4
