### ISSUE TITLE
URL in comments rel="nofollow"?

### ISSUE THREAD

**Issue by r-moon** [Viima/jquery-comments#16]
Hello again,

Is there any way to attach a rel="nofollow" attribute to the URLs in the comments?.

Thank you.

**Comment by jjtykkyl** [comment]
Usually the case is that the user is required to log in before one can post a comment. Therefore the links are usually relevant but I definitely agree with you if the library is used without login as it increases the chance of spam. If you like, you can implement the functionality so that it can be enabled/disabled and then create a pull-request. I'll be more than happy to check it out.

Ps. Links are created in a function named "linkify"

**Comment by r-moon** [comment]
Thank you for your reply. I regret my javascript knowledge is very limited and I am not able to do it myself, but you helped me anyway because in that "linkify" function I can write the attribute I was talking about directly althought you are right, the comments are protected requiring a log in so I will let them that way knowing I can sort this out with the above.

Again thank you.
