### ISSUE TITLE
Send comment on "Enter" event

### ISSUE THREAD

**Issue by SergioGregorutti** [Viima/jquery-comments#19]
Hi,

Many users are familiar with send a comment on Enter (thanks to Facebook?).

I think that it will be a good improvement to have the option of send the comment on Enter event.

Thanks!

**Comment by jjtykkyl** [comment]
I thought about this when implementing the library but decided not to implement this as it confuses users in some use cases (I actually deleted this feature in our other project due to confusion). Again, you are more that welcome to implement this yourself as long as this feature can be enabled and disabled (disabled by default).

**Comment by SergioGregorutti** [comment]
Thanks for your response. I'm not sure if I can resolve this but I'll try to do my best. If I have news I'll let you know.

**Comment by jjtykkyl** [comment]
Just to let you know, I am going to implement some new features to this library in the beginning of next month so I could do this as well.

**Comment by SergioGregorutti** [comment]
Cool. You made a really good work with this library. It deserves to be more popular. I'll share it with my co-workers.

Thanks.

**Comment by jjtykkyl** [comment]
I'm happy to let you know that this feature has been implemented to version 1.1.0. You can enable the functionality by setting the new variable "postCommentOnEnter" to true
