### ISSUE TITLE
How does this plugin know who I am?

### ISSUE THREAD

**Issue by webbird** [Viima/jquery-comments#4]
I really like this plugin, but there's one thing I don't understand. How does it know who I am? There's no field to insert a name. Do you have an example of how to manage this?

**Comment by jjtykkyl** [comment]
There are a few ways to recognize the current user. As you initialize the library you should provide the "profilePictureURL" which is used to show the comments created by the current user AND on the lefthand side before the new comment placeholder as it indicates who is going to publish the new comment.

The new comment objects contain also the "profilePictureURL" field and it's pre-filled from the field mentioned above (:591). However, when the comment is saved to the backend the profilePictureURL may be overridden by the server. Same goes for the author name: the name is set to "You" by default (:590) but may be overridden by the server.

In addition, the comment objects contain a field called "createdByCurrentUser" which can be used to determine whether the comment is created by the current user or not. jquery-comments is using this information to add certain class to the html element and enable editing for instance.

**Comment by webbird** [comment]
I have seen that options, but I'm not sure how this should be used in production. I have created this solution now (for use with a CMS):

* If the user is logged in, the "youText" is filled with his name. (I am doing this by adding a data-username attribute to the comments div, but this is quite unsecure)
* If the user is NOT logged in (guest user), a name field is added to the form.

If comments are open for guest users, it would be nice to let them enter a name, instead of calling all of them "You" or "Guest" or something. ;)

**Comment by jessenieminen** [comment]
Thanks for the inquiry @webbird ! As @jjtykkyl already wrote, it's the responsibility of the backend to identify the user who makes the POST request for creating a new comment and then add the reference to that user's specific information. 

Doing it in the backend ensures that a user can't fake comments from others and thus this isn't something that jquery-comments should have any further built in functionality for.

We added the special handling for changing the current user's name to 'You' so that it would be easier to distinguish themselves for the user and if you want to revert that and fall back to the real name of the user, feel free to do that just like you have, but it's not something we're planning to change.

Furthermore, jquery-comments is designed to be used in web applications, where it's encouraged to  identify people's identities, e.g. having them be logged in. As you mentioned, the library also supports guest comments for those cases where it's necessary to give people the possibility to comment without being logged in but we have no plans to add support for anonymous commenting with a user entered name. So your current implementation of adding a name field to the form sounds like a reasonable workaround as long as you make sure your backend clearly distinguishes between guest users with a name and 'real' logged in users.
