### ISSUE TITLE
An option of hiding all comments and appending total comments count, attachments count, replies count, etc..

### ISSUE THREAD

**Issue by wictorio** [Viima/jquery-comments#48]
![comments](https://cloud.githubusercontent.com/assets/18551881/14928821/7a297c8a-0e5a-11e6-9128-d13b1f226bb8.png)
Hi
I am having multiple jquery-comments instances on my page and each contains several comments. All of it makes the page navigation a nightmare. I decided to hide all the comments by default and show them upon selection from the navigation panel. I managed to include a 'Hide' element to the Comments Navigation panel. I set it to default and all works fine but now I'd like to append some basic info with a total count of the comments, have a look at the attached picture. How can I do it?
Thanks
--Victor

**Comment by jessenieminen** [comment]
Hi,
These are quite custom requests and we don't see them useful in the basic implementation of the library so there are no plans to implement them in the near future from our behalf.

For implementing that "43 comments" display feature, there are basically two things you need to do:

1) Make changes to render() function so that it by default hides the comment container div with `display: none` and add that div after it.
2) Make changes to navigationElementClicked() function so that it shows or hides the comments and that  placeholder div depending on which tab was clicked
