### ISSUE TITLE
How to I can get JSON comments from container?

### ISSUE THREAD

**Issue by brygom** [Viima/jquery-comments#60]
Hello, I using this great component in my web app, but I need using JQuery get JSON comments, I already trying using this, but nothing happened.

`var comments = $('#comments-container').data('comments').getComments();`

Maybe can help..

**Comment by jjtykkyl** [comment]
You were doing it right so I need a bit more information in order to help you. What did the function return? The comments are stored in a dictionary named "commentsById" to which you can get a reference by:
````
$('#comments-container').data('comments').commentsById
````
The "getComments" function only converts this dictionary into an array. Can you get a reference to this dictionary?

**Comment by brygom** [comment]
Thank for you reply, in fact I need it the reference for dictionary, your answer is correct and work for me.
