### ISSUE TITLE
Disable postComments

### ISSUE THREAD

**Issue by r-moon** [Viima/jquery-comments#9]
Hi,
I am trying to disable postComments to users without an account in my application, I almost have it but just wanted to ask if there is shorcut to do it like the ones in the script such as, I could not find it:
enableUpvoting: false,
enableEditing: false,

example: enable postComments: true/false.

Thank you very much

**Comment by jjtykkyl** [comment]
Unfortunately there is no such feature in jquery-comments. I utilize jquery-comments in another project as well where I check the restrictions in callbacks and I recommend you to do the same. If that's not suitable for you for some reason, I recommend you to just hide the send -buttons with css and/or disable the text-areas. Due to security issued you need to validate the user in the backend anyway...

**Comment by r-moon** [comment]
Thank you for your fast reply, I understand the scenery, so I will go the way you suggested.

All the best.
